### ISSUE TITLE
`compiler.add_source` multiple rules

### ISSUE THREAD

**Issue by jpds** [VirusTotal/yara-x#119]
`compiler.add_source` doesn't appear to support adding multiple rules at once, only the first one defined is parsed.

**Comment by plusvic** [comment]
`compiler.add_source` receives arbitrary source code that can include multiple rules and all of them are parsed. Are you experiencing something else?

**Comment by jpds** [comment]
Hmm, none of the tests at https://github.com/VirusTotal/yara-x/blob/main/lib/src/compiler/tests/mod.rs define two rules in a single function call, minus the ones at lines 377-378 (but that one has one that's ignored)

For https://github.com/delroth/grep-nixos-cache/pull/4 - I had to split the rule definitions into separate files to make this work.

**Comment by plusvic** [comment]
There are tests that contains more than one rule in a single call to `add_source`, for instance:

https://github.com/VirusTotal/yara-x/blob/b88f4d9a01f49bb6be2338136bdab1defaf12595/lib/src/compiler/tests/mod.rs#L373-L380

https://github.com/VirusTotal/yara-x/blob/b88f4d9a01f49bb6be2338136bdab1defaf12595/lib/src/compiler/tests/mod.rs#L540-L550

**Comment by jpds** [comment]
Apologies about this - I took a closer look at my code and one of my iterators was off.
