### ISSUE TITLE
Rule metadata C-API

### ISSUE THREAD

**Issue by codedninja** [VirusTotal/yara-x#120]
Sorry about opening another issue about this, I am not as knowledgeable with Rust as I thought. I tired to implement the C-API for rule's metadata but it hasn't gone as well as I have hoped. Thank you in advance!

Would it be possible to request the rule metadata be added to the C-API as well?

**Comment by plusvic** [comment]
Implemented in bfa57afde38bae9c9dae6828b5865f21b70948d1
