### ISSUE TITLE
Compiled rule with error: invalid UTF-8

### ISSUE THREAD

**Issue by antime** [VirusTotal/yara-x#127]
When i compile the rules and use the compiled rules to scan a file, one erroe occured with invalid UTF-8 character. But use the original rule scan the same file, it is normal.

**Comment by antime** [comment]
The content of the original rules is:

**Comment by plusvic** [comment]
For reference for future users landing here: this is because you must use the `--compiled-rules` option (or `-C`) to tell the `scan` command that the input is not a source file, but a binary file with compiled rules. Otherwise, it will try to read the binary file as a source file.
