### ISSUE TITLE
Missing include function

### ISSUE THREAD

**Issue by antime** [VirusTotal/yara-x#128]
![123](https://github.com/VirusTotal/yara-x/assets/17289600/06c2114c-ed9e-42c0-8c2a-a1059c165d26)
How to reference rules if they are distributed in two rule files？

I can use include in yara，but not work in yara-x

**Comment by plusvic** [comment]
If you compile two source files together (let's call them `file1.yar` and `file2.yar`), you can use a rule defined in one of them from the other. This is done like:

```
yr scan file1.yar file2.yar <TARGET_PATH>
```

Also, if both files are in the same directory `my_dir`, you can simply do:

```
yr scan my_dir <TARGET_PATH>
```

**Comment by antime** [comment]
I found the reason, it's because the rule file name cannot start with a number, which caused the problem. 
Thanks
