### ISSUE TITLE
YARA-X Features request

### ISSUE THREAD

**Issue by kfir206** [VirusTotal/yara-x#129]
Hi,
so happy for this x update.
we developed layer on the Yara that running yara scans of multiple files on windows OS automatically with our exe. its distributed till now over 170K machines so we have the experience with the tool.

my request:

1. classified the output to event viewer:
 a. Scan Started
 b. error
c. evidence found
d. scan completed

2.run as a service and read from specific directory like SYSVOL\Git Repo new yara rule files.

Im available here if it helps 
kfiro@cyray.io
+972508117000

**Comment by plusvic** [comment]
The goal for YARA-X is building the scanning engine and basic command-line tool, a full-fledged, Windows-specific scanning service is outside the scope for this project. This sounds like an interesting project, but it's too specific.

**Comment by kfir206** [comment]
And what about the logs output to event viewer?

**Comment by plusvic** [comment]
Same thing, that's a Windows-specific thing. I don't plan to write a Windows service, and sending the output for the command-line tool to the event viewer doesn't make too much sense. Sending to the event viewer makes sense when you have a long-running service in a Windows machine.

**Comment by kfir206** [comment]
and option for central log? even write to local file with classification of detection\errors.... today the use in logs command line output YARA is horrible

**Comment by plusvic** [comment]
I have a plan for providing a JSON structured output with the results of the scan. That output could be written to a file.

**Comment by kfir206** [comment]
Great

*Kfir Ozeri *| Cyber Security Engineer Team Leader
***@***.*** |  +972-508117000  |  www.CyRay.io <http://www.cyray.io/>
