### ISSUE TITLE
misisng yarax binary in /target/release after building

### ISSUE THREAD

**Issue by NKXK26** [VirusTotal/yara-x#146]
Hi creators of yarax, i am new to linux and currently i want to try yarax after learning yara.
so the problem i am facing is after i clone the yarax github repository, i try to build the release, and i get the finish release [optimized] at the end, but i cant see yarax inside the target/release.
may i know how to install yarax inside my oracle linux please. 
Thank you
![Screenshot 2024-06-25 211553](https://github.com/VirusTotal/yara-x/assets/105815343/62b28536-44b9-494e-9af0-dc342c8b1c1b)

**Comment by plusvic** [comment]
The final binary for the command-line tool is not named `yarax`, it's simply `yr` and you can see it in the `target/release` directory.
