### ISSUE TITLE
Can't compile compiled_rule.yar with YARA-X at python

### ISSUE THREAD

**Issue by HydraDragonAntivirus** [VirusTotal/yara-x#150]
Can't compile compiled_rule.yar with YARA-X at python https://github.com/HydraDragonAntivirus/HydraDragonAntivirus/tree/main/yara

**Comment by HydraDragonAntivirus** [comment]
Error compiling YARA rule:  error[syntax_error]: code is too complex or large
ion: any of them}
       |                                                                                                  ^ parser aborted here
       |
       = note: reduce the number of nested parenthesis or the size of your source code
Error: YARA rule compilation failed.

**Comment by plusvic** [comment]
That's a limitation in the current parser, but I'm working on a new version of the parser that removes this limitation.

**Comment by HydraDragonAntivirus** [comment]
Previously I got another issue but after changed the syntax I solved old magic issue.

**Comment by plusvic** [comment]
Fixed in the 0.6.0 release.

**Comment by HydraDragonAntivirus** [comment]
I forgot to update version sorry for that.
Error compiling YARA rule:  error[E115]: `entrypoint` is unsupported`
     --> line:14410:7
      |
14410 | $0 at entrypoint
      |       ^^^^^^^^^^ the `entrypoint` keyword is not supported anymore
      |
      = note: use `pe.entry_point`, `elf.entry_point` or `macho.entry_point`
Error: YARA rule compilation failed. Now I get this error which is fixable.

**Comment by plusvic** [comment]
Yes, you'll probably get a few other errors about escaped characters in regular expressions.
