### ISSUE TITLE
When compiling with Nuitka YARA-X python cause invalid YARA-X compiled rules file

### ISSUE THREAD

**Issue by HydraDragonAntivirus** [VirusTotal/yara-x#151]
https://github.com/VirusTotal/yara-x/blob/2c5fdd924e86e315f1f56d47a37910f09494a282/lib/src/compiler/errors.rs#L25
,https://github.com/HydraDragonAntivirus/HydraDragonAntivirus/blob/main/antivirus.py
https://github.com/HydraDragonAntivirus/HydraDragonAntivirus/blob/main/nuitka.txt
When compiling with Nuitka YARA-X python cause invalid YARA-X compiled rules file, should I open this at Nuitka issues? Is this Nuitka related issue?

**Comment by plusvic** [comment]
Can you explain a little better what's the issue you are experiencing? It's not clear to me what are you trying to accomplish and which are the steps you are following.

**Comment by HydraDragonAntivirus** [comment]
When there too many magics like } then it can't compile that.

**Comment by HydraDragonAntivirus** [comment]
It just show that error message:  An error occured while running with YARA-X: invalid YARA-X compiled rules file An unexpected error occurred: invalid YARA-X compiled rules file https://github.com/HydraDragonAntivirus/HydraDragonAntivirus/blob/main/antivirus.py#LN1249

**Comment by HydraDragonAntivirus** [comment]
I now installed YARA-X 0.5.0 if it's fixed that I can feedback that.

**Comment by plusvic** [comment]
`invalid YARA-X compiled rules file` occurs when you pass to YARA-X a file with already compiled files that was not generated by YARA-X itself or is somewhat corrupted. For example, you can't compile rules with YARA and pass the resulting binary file to YARA-X.

**Comment by HydraDragonAntivirus** [comment]
![image](https://github.com/VirusTotal/yara-x/assets/142328963/0abfe954-1423-4564-877b-2139d6535922)
I compilied YARA-X with YARA-X but when I convert to executable with Nuitka it causes this error.

**Comment by HydraDragonAntivirus** [comment]
I find a solution probably for Nuitka. Please wait. I'm going to close issue if this fix helps me to fix problem.

**Comment by HydraDragonAntivirus** [comment]
The solution : `python -m nuitka --standalone --onefile --include-module=yara_x --include-data-file=C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages\yara_x\yara_x.pyd=yara_x/yara_x.pyd compileryarax.py `if doesn't work then do ` python -m nuitka --standalone --onefile --include-module=yara_x compileryarax.py`  compileryarax.py :
```
import yara_x

def compile_yara_rule(rule_path):
    try:
        with open(rule_path, 'r', encoding='utf-8') as f:
            rule = f.read()
        
        # Compile the rule using yara_x.compile
        compiled_rule = yara_x.compile(rule)
        return compiled_rule
    except FileNotFoundError:
        print(f"Error: Rule file '{rule_path}' not found.")
        return None
    except yara_x.CompileError as e:
        print("Error compiling YARA rule: ", e)
        return None
    except Exception as e:
        print("An unexpected error occurred:", e)
        return None

def save_compiled_rule(compiled_rule, output_path):
    try:
        # Use serialize_into method to serialize the compiled rule to a file
        with open(output_path, 'wb') as f:
            compiled_rule.serialize_into(f)
        print(f"Compiled rule saved to '{output_path}'")
    except IOError as e:
        print(f"Error saving compiled rule to '{output_path}':", e)
    except Exception as e:
        print("An error occurred while saving the compiled rule:", e)

def main():
    rule_path = "yaraxtr.yar"
    output_path = "yaraxtr.yrc"

    compiled_rule = compile_yara_rule(rule_path)
    if compiled_rule is None:
        print("Error: YARA rule compilation failed.")
        return

    save_compiled_rule(compiled_rule, output_path)
    print("YARA rule compiled and saved successfully.")

if __name__ == "__main__":
    main()
```
Then run compileryarax.exe. Done! It's now working.
Conculusion: It's not related with yara_x it's related with Nuitka. So it's related with me because I somehow broke Nuitka then fixed after doing that. You can see my other issues and then you can understand it. But real issue is you must compile yara_x file with executable yara_x file not extension with .py python script because it cause this problem.

**Comment by HydraDragonAntivirus** [comment]
![image](https://github.com/VirusTotal/yara-x/assets/142328963/9f140be2-7b4c-4072-b1fd-c728b1e396ef)
The first one is executable one second is script one. There is the difference.

**Comment by HydraDragonAntivirus** [comment]
![image](https://github.com/VirusTotal/yara-x/assets/142328963/e494f776-fae3-4473-b314-99a401c3ba85)
If you still get this recompile again or report this issue at Nuitka.

**Comment by HydraDragonAntivirus** [comment]
They are same file I looked the HEX only difference is datetime

**Comment by HydraDragonAntivirus** [comment]
I thought I solved.  So sorry for that but that's not solved still get same error. My theory is incorrect

**Comment by plusvic** [comment]
If you run the same `compileryarax.py` file using Python directly (without using Nuitka), it works?

**Comment by HydraDragonAntivirus** [comment]
It works then I use with antivirus.exe as antivirus.py but after used Nuitka it become broken

**Comment by plusvic** [comment]
If you don't mind I'll close this issue because it looks like it's an issue with Nuitka, not with YARA-X itself.

**Comment by HydraDragonAntivirus** [comment]
Okay thank you!
