### ISSUE TITLE
Feature Request: JSON Output Option for scan Command in yr CLI

### ISSUE THREAD

**Issue by ousbaailyas** [VirusTotal/yara-x#156]
Firstly, thank you for your excellent work on the yara-x tool. It has been incredibly valuable for cybersecurity community.

I have a feature request that I believe would enhance its usability further. Currently, the dump command supports outputting results in JSON format, which is extremely useful for automated processing. However, the scan command does not seem to have a similar option for JSON output.

Would it be possible to add an option to output scan results in JSON format for the scan command in future releases? This feature would greatly improve the integration and automation capabilities of the tool.

Thank you for considering this request and for your continued efforts in developing such a powerful tool.

**Comment by plusvic** [comment]
That's a good idea, thank you for your feedback.

**Comment by plusvic** [comment]
Implemented in #161
