### ISSUE TITLE
Move wasm functions and dependencies behind a cargo feature

### ISSUE THREAD

**Issue by jonathan-d-zhang** [VirusTotal/yara-x#164]
`wasmtime` and its dependencies increase compile time and executable size unnecessarily if we aren't using features to output wasm, like [`yara_x::Compiler::wasm_emit_file`](https://docs.rs/yara-x/0.5.0/yara_x/struct.Compiler.html#method.emit_wasm_file).

## Build measurements
Generated using an i7-13700k, using a clean build of the [example script](https://docs.rs/yara-x/0.5.0/yara_x/index.html#example) from the docs. The `Cargo.toml` I used:

```toml
[package]
name = "testing"
version = "0.1.0"
edition = "2021"

[dependencies]
yara-x = "0.5.0"
```

### `cargo build --release --timings`
I was doing other stuff on my computer while running this, so it's not perfect, but it gives a good idea.
![image](https://github.com/user-attachments/assets/c91cb694-b60c-4ebd-abd6-06b04a27a819)

I think at least 5 seconds could be saved here.

### `cargo bloat --release --crates`
See [`cargo bloat`](https://github.com/RazrFalcon/cargo-bloat)
```
 File  .text     Size Crate
 9.7%  21.1%   2.2MiB yara_x
 5.5%  12.1%   1.3MiB cranelift_codegen
 4.1%   9.1% 981.8KiB std
 3.1%   6.7% 729.4KiB wasmparser
 2.8%   6.0% 652.9KiB protobuf
 1.9%   4.2% 458.6KiB wasmtime
 1.9%   4.2% 457.3KiB regex_automata
 1.8%   4.0% 429.8KiB wasmtime_cranelift
 1.5%   3.4% 364.6KiB [Unknown]
 1.1%   2.4% 263.9KiB yara_x_parser
 1.0%   2.2% 239.4KiB zstd_sys
 1.0%   2.2% 234.9KiB walrus
 0.9%   2.0% 217.8KiB aho_corasick
 0.8%   1.8% 198.8KiB regex_syntax
 0.8%   1.8% 189.6KiB gimli
 0.8%   1.7% 179.5KiB cpp_demangle
 0.7%   1.6% 169.0KiB pest
 0.5%   1.1% 116.5KiB wasmtime_runtime
 0.5%   1.0% 109.7KiB x509_parser
 0.5%   1.0% 106.8KiB wasmtime_environ
 4.0%   8.8% 952.2KiB And 80 more crates. Use -n N to show more.
45.7% 100.0%  10.6MiB .text section size, the file size is 23.1MiB
```

## Summary
With incremental builds this isn't really an issue for development (and debug builds are much faster to begin with), and caching helps a lot in CI, but clean CI builds may need to happen frequently for dependency bumps, for example.

Moving the wasm functions and dependencies to a cargo feature would reduce build times, especially in CI runners with less available parallelism and CPU speed.

**Comment by plusvic** [comment]
I'm not sure what's the proposal here. Bear in mind that wasmtime is not an optional dependency, it's required to be able to compile rules and scan files.

**Comment by jonathan-d-zhang** [comment]
Hi plusvic, thanks for the quick response. I was originally proposing that `wasmtime` be moved behind a [cargo feature](https://doc.rust-lang.org/cargo/reference/features.html) like `text-module`. I didn't know that it was a required dependency.

I'm not entirely familiar with the implementation details; could you explain what it is used for or provide a link to an explanation? I didn't find anything on https://virustotal.github.io/yara-x/.

**Comment by plusvic** [comment]
The boolean expression in a rule condition are translated to WebAssembly code, the `wasmtime` create provides the runtime for executing this code when the rule is evaluated, that's why `wasmtime` is not optional. Without `wasmtime` we can't evaluate rule conditions.

**Comment by plusvic** [comment]
Closing this issue as `wasmtime` is not optional.
