### ISSUE TITLE
Ignore "warning[duplicate_import]"?

### ISSUE THREAD

**Issue by VIT-JNE** [VirusTotal/yara-x#165]
Hello esteemed ladies and gentlemen,

is there a way to ignore duplicate_import-Warnings in the commandline, when I do scan?
I am trying to write a script for colleagues with as few interaction and info as possible and concentrate the results on the minimum.
And the duplicate import warning is the one thing I get tens or hundreds of times and I can't think of a case. where that is dangerous.

I tried it with a pre-compiled ruleset, but that has other issues I will do a separate thread for.

Thanks for the work in general. Yara-x rocks very hard =)

Best regards
JNE

**Comment by plusvic** [comment]
Yes, you can use `--disable-warnings=duplicate_import`

See: https://virustotal.github.io/yara-x/docs/intro/using-the-cli/#--disable-warnings--w

**Comment by VIT-JNE** [comment]
Same as on the other issue:
Thanks for the damn quick help.
With your source from the other issue, I already found it at the same time. ^^

Issue can be closed as successful.

Keep up the good work. =)

JNE
