### ISSUE TITLE
"Error[E017] invalid UTF-8 character" when using compiled ruleset .yarc

### ISSUE THREAD

**Issue by VIT-JNE** [VirusTotal/yara-x#166]
Hello esteemed ladies and gentlemen,

when I do
.\yr.exe compile .\yara-forge-rules-core
and get an output.yarc to use:
.\yr.exe scan output.yarc C:\someFoobar
then I get the error:
Error[E017]: invalid UTF-8
in the .yarc-File

Do I misunderstand something in the intended use of compiled rules?
Or do I get some weird error, that everyone else doesnt encounter?

Best regards
JNE

**Comment by plusvic** [comment]
You must use the `-C` option to indicate that the input file is not a source file, but an already compiled file.

**Comment by plusvic** [comment]
See: https://virustotal.github.io/yara-x/docs/intro/using-the-cli/#--compiled-rules--c

**Comment by VIT-JNE** [comment]
Damn.
Thank you. That is a nice source. That will help a lot on other things too. Thanks.

It's a bit sad there does not seem to be any hint in --help about this.

Can I change the issue to:
"yr.exe --help compile" should be a thing? ^^'

JK. You can close the issue as successful.
Sorry.
Thanks again.
JNE
