### ISSUE TITLE
So uh....how do you build this?

### ISSUE THREAD

**Issue by DigiAngel** [VirusTotal/yara-x#169]
Lot's of cool information in README.md, but nothing on making, installing.  No INSTALL doc or information in the docs directory so.....how do I build this thing?

**Comment by plusvic** [comment]
You can find some information here:
https://virustotal.github.io/yara-x/docs/intro/installation/

In general the build process is pretty standard in all Rust projects.

**Comment by DigiAngel** [comment]
Brilliant..thank you.
