### ISSUE TITLE
Possibility to scan files by chunks

### ISSUE THREAD

**Issue by qjerome** [VirusTotal/yara-x#175]
First of all, thank you @plusvic for porting Yara to Rust! :smile:

I am looking to integrate Yara-X into my project to scan files in real-time, but I have a question that I couldn't find an answer to in the documentation.

**Is it possible to scan a file in chunks (without resetting the scanner)?**
I looked at the code, and it does not seem obvious to me how to do it without implementing new APIs.

I see several advantages of having such functionality:
- Easy scanning of large files using buffered read
- Ability to scan with Yara while performing other chunk processing tasks (e.g., file hashing) on the file/data with minimal impact on performance

If you believe this feature can be implemented and it makes sense to you, I can contribute to its development if you need.

**Comment by plusvic** [comment]
Unfortunately this is not possible, and won't be possible in the future for multiple reasons. YARA's design relies on the premise that it has access to the whole file, for instance, modules need to parse the file, and many file formats can't be parsed in chunks. Also, the `intXX` functions are hard to implement without having access to every offset of the file during the condition evaluation.

In the future I also want to add uncompressing features (i.e: the ability to scan content inside ZIP files, installers, etc), and in most cases this will require reading the whole compressed file. So, in resume, scanning in chunks or streaming mode is not really feasible.

**Comment by qjerome** [comment]
Thanks for your reply ! I'll do without it then :wink:
