### ISSUE TITLE
I want to load precompiled Yara rules in Rust code.

### ISSUE THREAD

**Issue by coalooball** [VirusTotal/yara-x#176]
After using the command:
```sh
yr compile some_files.yar -o some_files.yarc
```

how can I use the API in `yara_x` to load `some_files.yarc` and match content? 
I've looked through the interfaces of ```rust yara_x::Compiler``` and ```rust yara_x::Rules``` but haven't found a function to achieve this. 
I would greatly appreciate it if you could guide me on how to write the code for this. Thank you very much!

**Comment by plusvic** [comment]
You must use [Rules::deserialize_from](https://docs.rs/yara-x/latest/yara_x/struct.Rules.html#method.deserialize_from), for instance:

```rust
let file = File::open(rules_path)?;
let rules = Rules::deserialize_from(file)?;
```

**Comment by coalooball** [comment]
> You must use [Rules::deserialize_from](https://docs.rs/yara-x/latest/yara_x/struct.Rules.html#method.deserialize_from), for instance:
> 
> ```rust
> let file = File::open(rules_path)?;
> let rules = Rules::deserialize_from(file)?;
> ```

Thank you very much. I previously thought it was a similar interface to yr_rules_load, so I couldn't find it.

**Comment by coalooball** [comment]
> You must use [Rules::deserialize_from](https://docs.rs/yara-x/latest/yara_x/struct.Rules.html#method.deserialize_from), for instance:
> 
> ```rust
> let file = File::open(rules_path)?;
> let rules = Rules::deserialize_from(file)?;
> ```

Thank you very much. I previously thought it was a similar interface to `yr_rules_load`, so I couldn't find it.
