### ISSUE TITLE
Add type hinting and documentation to Python module

### ISSUE THREAD

**Issue by tubarao312** [VirusTotal/yara-x#178]
In the documentation for PyO3, they give an example of how to add type hints to Python. I'd personally find this very useful: https://pyo3.rs/v0.22.2/python-typing-hints

I've worked with PyO3 and Python before, if you want I can do this myself and open a PR with type hints as well as docs and examples copied from the official documentation. Let me know if my help out be appreciated!

**Comment by plusvic** [comment]
Sure! This contribution is appreciated, if you want to work on that and send a PR, it's welcomed.

**Comment by latonis** [comment]
Manual implementation of the stub file done in https://github.com/VirusTotal/yara-x/commit/a417f493abc217e3328be9392ecd24322150bf0d, but generating automatically would still be desired. I am looking into it :)
