### ISSUE TITLE
Compilation as Go binding fails II

### ISSUE THREAD

**Issue by steffenfritz** [VirusTotal/yara-x#194]
I built the C library as documented here: https://virustotal.github.io/yara-x/docs/api/c/c-/#building-the-c-library without errors.

Adding it to a project with import yarax "github.com/VirusTotal/yara-x/go" and building the Go code fails with:

```
$ task build
task: [build] go build -gcflags="-m" -buildmode=pie -ldflags "-X main.Version=$VERSION -X main.Build=61e36f0 -w -s"
# github.com/VirusTotal/yara-x/go
vendor/github.com/VirusTotal/yara-x/go/compiler.go:265:5: could not determine kind of name for C.yrx_compiler_add_source_with_origin
vendor/github.com/VirusTotal/yara-x/go/compiler.go:369:5: could not determine kind of name for C.yrx_compiler_errors_json
vendor/github.com/VirusTotal/yara-x/go/compiler.go:391:5: could not determine kind of name for C.yrx_compiler_warnings_json
task: Failed to run task "build": exit status 1
```

Machine:

1. MacOS
2. ARM64 - M1
3. MacOS 14.6.1
4. Homebrew used for rust and cargo installation

I think that might be again a version problem like #122 

Thanks and best regards,

Steffen

**Comment by plusvic** [comment]
Which version of the C library did you install? Does it match the version of the Go library?

**Comment by steffenfritz** [comment]
I updated the C library (missed that, sorry), the error changed to:

````
github.com/VirusTotal/yara-x/go
vendor/github.com/VirusTotal/yara-x/go/scanner.go:81:3: could not determine kind of name for C.YRX_ON_MATCHING_RULE
task: Failed to run task "build": exit status 1

````

I use upstream of the yara-x repo and the Go module v0.7.0.

I see that v0.8.0 is the latest upstream, but it is not available via `go get`

**Comment by plusvic** [comment]
Oh, that's right, I forgot to publish the Go module. Now it's done.

**Comment by steffenfritz** [comment]
Thanks, now I could fetch the new Go module.

But still, also after rebuilding everything:

`````
steffen@ceres ~/g/s/g/s/FileTrove (main)> go build -a
# github.com/VirusTotal/yara-x/go
vendor/github.com/VirusTotal/yara-x/go/scanner.go:80:3: could not determine kind of name for C.YRX_ON_MATCHING_RULE
steffen@ceres ~/g/s/g/s/FileTrove (main) [1]>
`````

**Comment by steffenfritz** [comment]
Maybe I am completely confused now, but I cannot find "YRX_ON_MATCHING_RULE" in https://github.com/VirusTotal/yara-x/blob/main/capi/include/yara_x.h

I see yrx_scanner_on_matching_rule and the second argument is that callback. But the definition is missing, right?

**Comment by plusvic** [comment]
`YRX_ON_MATCHING_RULE` changed to `YRX_RULE_CALLBACK`. You are probably using a the most recent version of the C API in master with version 0.8.0 of the Golang library.
