### ISSUE TITLE
Suggestion about rules compilation

### ISSUE THREAD

**Issue by RRancio** [VirusTotal/yara-x#196]
i noticed that the yara-x compiled rules is kinda readable compared to default yara compiled rules

default yara:
![imagen](https://github.com/user-attachments/assets/a568860f-31d7-4363-a6f1-ade8d197f25d)

yarax:
![imagen](https://github.com/user-attachments/assets/0f91fe85-a99d-41ef-aa98-661abbc78eaa)

im not sure if this are made on purpose but i think is better to make Compiled rules less readable for humans

**Comment by plusvic** [comment]
IMHO that's not really an issue, what's the point of making the compiled rules "unreadable" to humans? I could scramble or compress certain data inside the compiled rules, but that doesn't change the fact that all the data is there. Which is exactly your concern?

**Comment by plusvic** [comment]
Compiled rules do not intend to keep your rules private, the only intention is avoiding to compile the rules again. Even if rule names and identifiers are scrambled somehow, they could be reverse-engineered. Also, the old YARA doesn't do anything special in that regard, rule and string identifiers are also legible in compiled rules produced by YARA.
