### ISSUE TITLE
Crash under Windows only when using --release

### ISSUE THREAD

**Issue by GamingGuy003** [VirusTotal/yara-x#204]
When scanning any file under windows when using the --release build, panic occurs. This does not happen when simply running the default debug build

This is the full output
```thread '<unnamed>' panicked at C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\yara-x-0.8.0\src\scanner\mod.rs:292:14:
called `Result::unwrap()` on an `Err` value: unknown import: `yara_x::modules::macho::macho.export_hash@@su` has not been defined
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

If anything else is needed please let me know

**Comment by plusvic** [comment]
This looks like you are using compiled rules that were generated with an older version of YARA-X. Make sure that you have the latest version of YARA-X in both the system that produces the compiled rules and the system that uses the compiled rules.

**Comment by GamingGuy003** [comment]
The rules were compiled locally by the same program due to you mentioning it not being a good idea to ship precompiled ones in the other issue #200 . I recompiled them again just to make sure and that seems to have fixed them. Strange since the same behaviour could not be observed when simply running `cargo run`, only with `cargo run --release`. Thank you for the hint!
