### ISSUE TITLE
Disable recursive scanning by default

### ISSUE THREAD

**Issue by r0ny123** [VirusTotal/yara-x#211]
Currently, `yara-x` performs recursive scanning by default, even if a specific path is mentioned. This behavior can be unexpected and lead to unintended scans of subdirectories. To improve usability and align with standard expectations, it would be better if recursive scanning were disabled by default, similar to YARA's behavior. Users who wish to enable recursive scanning should explicitly use the `-r` flag.

**Comment by plusvic** [comment]
Fixed in https://github.com/VirusTotal/yara-x/commit/6f45b2fd6b25b31e57bc108c4bf8977e175a88a1

**Comment by r0ny123** [comment]
Thanks a lot.
