### ISSUE TITLE
Inconsistent output formatting and unexpected symbols in `yr` scan command output

### ISSUE THREAD

**Issue by r0ny123** [VirusTotal/yara-x#212]
The output formatting is inconsistent when running `yr` and `yara`. Specifically, `yr` prints the rule name followed by the full path of the matched file, which is quite lengthy and less readable, whereas `yara` only prints the filenames and subdirectories when the -r flag is supplied.

Additionally, the `yr` command output includes some unexpected `?` symbols in front of the path, which seems to be incorrect.

```
C:\Users\rony\MAL_FAMILY\SPARROWDOOR\LOADER>yr scan draculoader.yar .
generated_rule \\?\C:\Users\rony\MAL_FAMILY\SPARROWDOOR\LOADER\other\2531891691ef674345f098ef18b274091acdf3f2808cca753674599c043ccd7d

C:\Users\rony\MAL_FAMILY\SPARROWDOOR\LOADER>yara draculoader.yar . -r
generated_rule .\other\2531891691ef674345f098ef18b274091acdf3f2808cca753674599c043ccd7d
```

**Comment by plusvic** [comment]
The prefix `\\?\` is still shown, but only when the target path passed to the CLI is an absolute path. This is a Windows thing, where absolute file paths are internally like that. The prefix could be removed, but it's not recommended. I'll keep it for now.

https://stackoverflow.com/questions/41233684/why-does-my-canonicalized-path-get-prefixed-with
https://users.rust-lang.org/t/understanding-windows-paths/58583
