### ISSUE TITLE
Hexadecimal output formatting differs between `yr` and `yara`

### ISSUE THREAD

**Issue by r0ny123** [VirusTotal/yara-x#214]
When running scans with the `-s` flag, the `yr` command outputs matched strings in a different format compared to `yara`. `yr` displays the output in escaped hexadecimal, while `yara` displays it without escape sequences, making it more readable. The `yara` output format is preferable for clarity.

**Comment by plusvic** [comment]
`yara` makes a distinction between text patterns and hex patterns. For hex patterns it shows the bytes without escape sequences and separated by spaces (like `61 62 00 00`), and for text patterns and regexps it does the same thing as `yara-x` (like `ab\x00\x00`). Should we show hex patterns in a special way for better legibility, or should we show every pattern in the same way for homogeneity?

**Comment by wxsBSD** [comment]
I like the behavior of yara here. By displaying hex patterns in that way it makes it easier to compare a match to the pattern.

**Comment by r0ny123** [comment]
I'd prefer to see `yara-x` follow YARA's formatting for better legibility and uniformity across different types of patterns. The escape sequences, like `\x00\x00`, make it harder to quickly interpret the output, so having the cleaner, more readable format from YARA would be really helpful. It would be great if we could keep the YARA-style hex formatting across the board.

**Comment by r0ny123** [comment]
@plusvic, yara-x still displays the output in escaped hexadecimal while using `-s` flag.

**Comment by plusvic** [comment]
> @plusvic, yara-x still displays the output in escaped hexadecimal while using `-s` flag.

You're right, there was a regression after merging https://github.com/VirusTotal/yara-x/pull/239
