### ISSUE TITLE
Text and regex-based rules don't work as expected

### ISSUE THREAD

**Issue by XBO-TNL** [VirusTotal/yara-x#236]
Hello everyone,
I'm working on integrating Yara-X into an existing application that currently integrates Yara.
Since the application is mostly developed in Rust, I expect Yara-X to provide a more seamless integration.

One of the tests I'm using from the old integration testsuite is the scanning of basic EICAR samples (https://www.eicar.org/download-anti-malware-testfile/). For this purpose I've written a Yara rule and gathered a couple of other rules from publically available sources (https://yarahq.github.io/).
All of these rules work in Yara but not all of them work in Yara-X. I'm aware that not all Yara rules are 100% compatible as stated in the FAQ, but I'd expect these simple rules to match.

Attached is the ruleset I'm using to scan the various eicar samples.
[yara-rules-xbo.yar.txt](https://github.com/user-attachments/files/17618059/yara-rules-xbo.yar.txt)

Based on my testing, only the following rules produce a match:
- XBO_Eicar_Test_Signature
- BINARYALERT_Eicar_Substring_Test

This leads me to suspect that something funky is happening in the parsing/matching of the initial part of the teststring: `X5O!P%@AP[4\PZX54(P^)7CC)7}`

If any more information is required to set up a reproduction scenario, please let me know in the comments.

**Comment by plusvic** [comment]
I'm trying to reproduce this issue without success. When I scan the EICAR file downloaded from https://secure.eicar.org/eicar.com.txt with the rules in [yara-rules-xbo.yar.txt](https://github.com/user-attachments/files/17618059/yara-rules-xbo.yar.txt) it produces the same results in both YARA and YARA-X. 

This is the output I get from the command-line tool:

```
./target/release/yr scan yara-rules-xbo.yar.txt eicar.txt
warning[text_as_hex]: hex pattern could be written as text literal
   --> yara-rules-xbo.yar.txt:129:9
    |
129 |            $a = {
    |   _________-
    |   _________-
130 | ||             58 35 4f 21 50 25 40 41 50 5b 34 5c 50 5a 58
...   ||
133 | ||             54 49 56 49 52 55 53 2d 54 45 53 54 2d 46 49
134 | ||             4c 45 21 24 48 2b 48 2a
    | ||___________________________________- this pattern can be written as a text literal
    | ||___________________________________- help: replace with "X5O!P%@AP[4\\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*"
    |
ELASTIC_Multi_EICAR_Ac8F42D6 eicar.txt
BINARYALERT_Eicar_Av_Test eicar.txt
BINARYALERT_Eicar_Substring_Test eicar.txt
TRELLIX_ARC_Malw_Eicar eicar.txt
SIGNATURE_BASE_SUSP_Just_EICAR eicar.txt
XBO_Eicar_Test_Signature eicar.txt
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 1 file(s) scanned in 0.2s. 1 file(s) matched.
```

Can you provide more details about how you are doing your tests?

**Comment by XBO-TNL** [comment]
hi @plusvic thank you for getting back to me. In my testcases I've taken the rules file attached, building up a `Rules` struct and using the `Scanner` with these rules to scan my files.

Upon further investigation, it looks like the rules don't match the samples I'm using directly. With slight modifications to the rules (i.e. removing modifiers like fullword, removing start and end anchors in the regexes), these all match. The culprit here is eicarcom2.zip where the modifiers in the rules don't make sense.

Based on my analysis, I think we can close this issue.

**Comment by plusvic** [comment]
Great, thanks!
