### ISSUE TITLE
Issue with Integer Range in YARA-X Rule Compilation

### ISSUE THREAD

**Issue by Jamba777** [VirusTotal/yara-x#238]
Hello, everyone,

I'm encountering an issue when trying to add a YARA rule to the compiler. The rule works fine in the standard YARA implementation but fails in YARA-X with the following error:
`
error[E027]: invalid integer
    --> line:2620:230
     |
2620 | ...3bf0300488b4424104889442430488b4c24[66232-66345]5953feff488b44247048890424c644240800e8a6d5ffff0fb644241048894424[25897-25993]8b...
     |                                        ^^^^^ this number is out of the valid range: [0, 65535]
`

It seems the integer range `[66232-66345]` exceeds the valid range `[0, 65535]` in YARA-X.

In the standard YARA, this rule compiles without any issues.

My question is:
Can I rewrite the out-of-range part `[66232-66345]` as something like `[65535][697-810]` or some equivalent workaround?

Thank you in advance for your help!

**Comment by fivlao** [comment]
Hi, 

Are you planning to add support for ranges more than 65535?
