### ISSUE TITLE
Statically Linking libyara_x_capii in golang

### ISSUE THREAD

**Issue by xorhex** [VirusTotal/yara-x#257]
New to cgo, how does one statically link `yara_x_capi` when building in go?

I've added this in the .go  file just under `package main`

```
// #cgo static_link pkg-config: --static yara_x_capi
````

Guessing there is a flag I need to set to get `cgo` to pick this up...?

I'm guessing by statically linking `yara_x_capi` that it will take care of this issue: `error while loading shared libraries: libyara_x_capi.so.0.11: cannot open shared object file: No such file or directory`

**Comment by plusvic** [comment]
This should build Go code with `yara_x` statically linked:

```
go build -tags static_link
```

You don't need modify the existing Go code, as that line is already contained in the code:
https://github.com/VirusTotal/yara-x/blob/0e2d6f227f606d38d4982f677ac96cf2ca6c9b70/go/main.go#L5C9-L5C20

**Comment by xorhex** [comment]
Gotcha - removed this line from my code

```
// #cgo static_link pkg-config: --static yara_x_capi
```

and added `-tags static_link` to my build command.  

Still getting **error**: `error while loading shared libraries: libyara_x_capi.so.0.11: cannot open shared object file: No such file or directory`


Here is my build process:
```
FROM amd64/golang:1.23.3 AS builder

RUN apt update
RUN apt upgrade -y
RUN apt install -y curl gcc git pkg-config libssl-dev
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /usr/src/app
RUN git clone https://github.com/VirusTotal/yara-x.git
WORKDIR /usr/src/app/yara-x
RUN cargo install --path cli
RUN cargo install cargo-c
RUN cargo cinstall -p yara-x-capi --release

ENV PKG_CONFIG_PATH=/usr/src/app/yara-x/target/x86_64-unknown-linux-gnu/release/

ENV CGO_ENABLED=1

WORKDIR /go/src/app
COPY go.mod .
COPY go.sum .
COPY *.go .

RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    go build -tags static_link -o ./yrc .

FROM scratch AS copytohost
COPY --from=builder /go/src/app/yrc ./yrc
```

Run it using: `sudo docker build --target copytohost --output type=local,dest=./ .`

**Comment by plusvic** [comment]
It turns out that building a fully static binary file is harder than expected. This is what worked for me:

```
cargo cinstall -p yara-x-capi --release
```

When using cgo, the Go compiler uses an external linker. We must tell that linker that we want a static executable, and that's what the `--ldflags '--extldflags "-static"'` argument does. For some reason that I don't understand yet, I had to pass `-lm` too, so that the linker can find some math functions. 

```
go build -tags static_link --ldflags '--extldflags "-static -lm"'
```

This seems to work but it raises two warnings that are very concerning:

```
/usr/bin/ld: /usr/local/lib/libyara_x_capi.a(std-ca74a2d9c5166d9f.std.c6eb78587944e35c-cgu.0.rcgu.o): in function `std::sys::pal::unix::os::home_dir::fallback':
/rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/sys/pal/unix/os.rs:747: warning: Using 'getpwuid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /usr/local/lib/libyara_x_capi.a(std-ca74a2d9c5166d9f.std.c6eb78587944e35c-cgu.0.rcgu.o): in function `<std::sys_common::net::LookupHost as core::convert::TryFrom<(&str,u16)>>::try_from::{{closure}}':
/rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/sys_common/net.rs:211: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```

The static binary that I got seems to work, but it's very simple and I don't know if this would work with more complex programs.

**Comment by xorhex** [comment]
Works for me as well (so far).  Thanks!
