### ISSUE TITLE
cannot use version 0.11.1

### ISSUE THREAD

**Issue by Aram-Ibrahim** [VirusTotal/yara-x#258]
version 0.11.1 gets me this 

~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/yara-x-0.11.1/src/scanner/mod.rs:297:14:
called `Result::unwrap()` on an `Err` value: unknown import: `yara_x::modules::cuckoo::cuckoo.registry.key_access@r@b` has not been defined

**Comment by plusvic** [comment]
I guess that's because you are using rules that were compiled with a previous version, right?. You'll need to recompile your rules.

**Comment by Aram-Ibrahim** [comment]
true

**Comment by plusvic** [comment]
Ok, then I'm closing the issue.
