### ISSUE TITLE
Discrepancy in `math.in_range` and `math.MEAN_BYTES` Handling Between `yara` and `yara-x`

### ISSUE THREAD

**Issue by r0ny123** [VirusTotal/yara-x#261]
There are some issues with the `math.in_range` function and the `math.MEAN_BYTES` constant when testing a YARA rule across both `yara` and `yara-x`. Here are the details:
The following rule is documented on [math module page](https://yara.readthedocs.io/en/latest/modules/math.html#)
```yara
 import "math"

rule test {
  condition:
    math.in_range(math.deviation(0, filesize, math.MEAN_BYTES), 63.9, 64, 1)
}
```
The errors are 
on yara:
```cmd
C:\Users\rony\Desktop>yara test.yar .
error: rule "test" in math1.yar(5): wrong arguments for function "in_range"
```
and on yara-x:

```cmd
C:\Users\rony\Desktop>yr scan test.yar .
error[E008]: unknown field or method `MEAN_BYTES`
 --> math1.yar:5:52
  |
5 |     math.in_range(math.deviation(0, filesize, math.MEAN_BYTES), 63.9, 64, 1)
  |                                                    ^^^^^^^^^^ this field or method doesn't exist
  |
error: 1 errors found
```

**Comment by r0ny123** [comment]
Thank you. Will the issue with the yara be addressed? @plusvic

**Comment by plusvic** [comment]
The problem was YARA was actually a typo in the documentation. It says "64,1" instead of "64.1", which means that you are passing an extra argument to the function.

**Comment by r0ny123** [comment]
Ah, completely overlooked. Thanks.
