### ISSUE TITLE
Feature Request: Add more ARM releases.

### ISSUE THREAD

**Issue by bladeswords** [VirusTotal/yara-x#267]
I would love it if yara-x had more releases for ARM CPU available.  

Specifically, I use ARM in AWS (graviton instances) and also to support the new ARM based Windows laptops from many vendors, which WSL inherits the ARM architecture.  Not to mention supporting the Raspberry Pi (and other similar ARM native systems).  

I will create a PR to attempt to update the build pipeline, however, I am unsure if the python package build pipeline should also be updated.

**Comment by plusvic** [comment]
#268 was merged and 77e9400 creates Python packages for ARM64 in Linux and Windows.
